name: Test, Build, and Release

on: [push]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y build-essential check pkg-config gcc libpthread-stubs0-dev glibc-thread-db

      - name: Build with Check
        run: |
          gcc -pthread operations.c check_operations.c -o check_operations \
          `pkg-config --cflags --libs check`

      - name: Run Unit Tests
        run: ./check_operations

  building-and-delivery:
    name: Build and Delivery
    permissions:
      contents: write
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Application
        run: gcc -pthread operations.c simplecalculator.c -o simplecalculator

      - name: Create tar.gz Archive
        run: tar -czvf simplecalculator.tar.gz simplecalculator

      - name: Release Artifact
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          files: simplecalculator.tar.gz
