name: Test, Build, and Release

on: [push]

jobs:
  static-test:
    name: Static Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install splint
      - name: Static test
        run: |
          splint --compdef --exportlocal simplecalculator.c operations.c

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y check pkg-config gcc libpthread-stubs0-dev

      - name: Build with Check
        run: |
          gcc operations.c check_operations.c -o check_operations \
          `pkg-config --cflags --libs check` -pthread -lpthread

      - name: Run Unit Tests
        run: ./check_operations

  building-and-delivery:
    name: Build and Delivery
    permissions:
      contents: write
    needs: [unit-test,static-test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Application
        run: gcc operations.c simplecalculator.c -o simplecalculator -pthread -lpthread

      - name: Create tar.gz Archive
        run: | 
          echo "EJBDVG" > neptun.txt
          tar -czvf simplecalculator.tar.gz simplecalculator neptun 

      - name: Release Artifact
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development Build"
          files: simplecalculator.tar.gz
